<?xml version="1.0" encoding="utf-8"?><Database Name="TvTuner" Class="TvTunerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=eric-pc;Initial Catalog=TvTuner;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TvTunerConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Episodes" Member="Episodes">
    <Type Name="Episode">
      <Column Name="EpisodeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SeriesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Season" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EpisodeNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Thumbnail" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VideoPath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Series_Episode" Member="Series" ThisKey="SeriesID" OtherKey="SeriesID" Type="Series" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movies" Member="Movies">
    <Type Name="Movies">
      <Column Name="MovieID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Thumbnail" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VideoPath" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Genre" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Series" Member="Series">
    <Type Name="Series">
      <Column Name="SeriesID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BannerImg" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Series_Episode" Member="Episodes" ThisKey="SeriesID" OtherKey="SeriesID" Type="Episode" />
      <Association Name="Series_ChannelSery" Member="ChannelSeries" ThisKey="SeriesID" OtherKey="SeriesID" Type="ChannelSery" />
      <Association Name="Category_Series" Member="Category" ThisKey="CategoryID" OtherKey="CategoryID" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Series" Member="Series" ThisKey="CategoryID" OtherKey="CategoryID" Type="Series" />
    </Type>
  </Table>
  <Table Name="dbo.Channels" Member="Channels">
    <Type Name="Channel">
      <Column Name="ChannelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Channel_ChannelSery" Member="ChannelSeries" ThisKey="ChannelID" OtherKey="ChannelID" Type="ChannelSery" />
    </Type>
  </Table>
  <Table Name="dbo.ChannelSeries" Member="ChannelSeries">
    <Type Name="ChannelSery">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChannelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SeriesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Channel_ChannelSery" Member="Channel" ThisKey="ChannelID" OtherKey="ChannelID" Type="Channel" IsForeignKey="true" />
      <Association Name="Series_ChannelSery" Member="Series" ThisKey="SeriesID" OtherKey="SeriesID" Type="Series" IsForeignKey="true" />
    </Type>
  </Table>
</Database>